name=input("What is your name? ")
age=input("What is your age? ")
country=input("Which country are you from? ")
print("Hello", name + "!")
print("You are", age, "years old.")
print("You are from", country + ".")